import time
print("Rocket Ready for Launch in 10 Seconds")
time.sleep(5)
print("Launch in 5")
time.sleep(1)
print("Launch in 4")
time.sleep(1)
print("Launch in 3")
time.sleep(1)
print("Launch in 2")
time.sleep(1)
print("Launch in 1")
time.sleep(1)
print("Pshhhhhh!")
