import random
import time

guests = ['ab', 'rock', 'mj']
#print(f"Sorry but {guests[0]} can't make it")
print(f"Current guests: {guests}")
time.sleep(1)
#select random guest
busy = random.choice(guests)
print(f"Apologise but it seem that {busy} can't make it today")
time.sleep(1)
print("In light of this news, joe is on his way")
time.sleep(1)
guests.insert(1, 'joe')
print(guests)
time.sleep(1)
print("On second thought, we've found a bigger table")
time.sleep(1)
guests.insert(0, 'barry')
guests.insert(2, 'obana')
guests.append('stalin')
print(guests)
time.sleep(1)
print("Actually, fuck all y'all fake niggas and fake cunts. only 2 of ny niggas coming")
time.sleep(1)
fakenigga1 = guests.pop()
print(fakenigga1)
time.sleep(1)
fakenigga2 = guests.pop()
print(fakenigga2)
time.sleep(1)
fakenigga3 = guests.pop()
print(fakenigga3)
time.sleep(1)
fakenigga4 = guests.pop()
print(fakenigga4)
time.sleep(1)
fakenigga5 = guests.pop()
print(fakenigga5)
print("you niggas GTFO")
print(guests)
print(fakenigga1 + " " + fakenigga2 + " " + fakenigga3 + " " + fakenigga4 + " " + fakenigga5)
time.sleep(1)
del guests[0]
del guests[0]
print(guests)
